# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170806_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='weight',
            new_name='current_weight',
        ),
    ]
