# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
