# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170809_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_feet',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_inches',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
