# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-21 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170815_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='week_start_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=6, null=True),
        ),
    ]
