# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-21 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_week_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='week_start_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=9, null=True),
        ),
    ]
