# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170729_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='Sets',
        ),
    ]
