# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170801_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
