# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
