# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_weight_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='user',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
