# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 15, 20, 55, 21, 377945)),
            preserve_default=False,
        ),
    ]
