# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20170815_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 21, 4, 16, 371264)),
        ),
    ]
